model_id = "mlx-community/gemma-3-27b-it-qat-4bit"
n_layers = 62
hidden_size = 4608
num_key_value_heads = 16
supports_tensor = true
tasks = ["TextGeneration"]
family = "gemma"
quantization = "4bit"
base_model = "Gemma 3 27B"
capabilities = ["text"]

[storage_size]
in_bytes = 16054266848
